/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.neubot.swig;

public class HttpClient {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected HttpClient(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HttpClient obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LibNeubotJNI.delete_HttpClient(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    LibNeubotJNI.HttpClient_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    LibNeubotJNI.HttpClient_change_ownership(this, swigCPtr, true);
  }

  public void handle_begin() {
    LibNeubotJNI.HttpClient_handle_begin(swigCPtr, this);
  }

  public void handle_body() {
    LibNeubotJNI.HttpClient_handle_body(swigCPtr, this);
  }

  public void handle_close() {
    LibNeubotJNI.HttpClient_handle_close(swigCPtr, this);
  }

  public void handle_connect() {
    LibNeubotJNI.HttpClient_handle_connect(swigCPtr, this);
  }

  public void handle_end() {
    LibNeubotJNI.HttpClient_handle_end(swigCPtr, this);
  }

  public void handle_flush() {
    LibNeubotJNI.HttpClient_handle_flush(swigCPtr, this);
  }

  public void handle_headers() {
    LibNeubotJNI.HttpClient_handle_headers(swigCPtr, this);
  }

  public HttpClient(Poller poller) {
    this(LibNeubotJNI.new_HttpClient(Poller.getCPtr(poller), poller), true);
    LibNeubotJNI.HttpClient_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public int connect(String family, String address, String port) {
    return LibNeubotJNI.HttpClient_connect(swigCPtr, this, family, address, port);
  }

  public int write(String data, long count) {
    return LibNeubotJNI.HttpClient_write(swigCPtr, this, data, count);
  }

  public int writes(String str) {
    return LibNeubotJNI.HttpClient_writes(swigCPtr, this, str);
  }

  public int flush() {
    return LibNeubotJNI.HttpClient_flush(swigCPtr, this);
  }

  public int code() {
    return LibNeubotJNI.HttpClient_code(swigCPtr, this);
  }

  public String reason() {
    return LibNeubotJNI.HttpClient_reason(swigCPtr, this);
  }

  public String header(String key) {
    return LibNeubotJNI.HttpClient_header(swigCPtr, this, key);
  }

  public long body_length() {
    return LibNeubotJNI.HttpClient_body_length(swigCPtr, this);
  }

  public String body_string() {
    return LibNeubotJNI.HttpClient_body_string(swigCPtr, this);
  }

}
